spring:
  datasource:
    url: jdbc:h2:mem:./catch-shopdb;
    # url=jdbc:h2:tcp://localhost/~/catchshop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

server:
  servlet:
    session:
      timeout: 1800
      tracking-modes: cookie
